spring:
  cloud:
    azure:
      active-directory:
        # Yml structure Learn doc link : https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-boot-starter-for-azure-active-directory-developer-guide?tabs=SpringCloudAzure4x
        enabled: true
        profile:
          # Specifies your Active Directory ID:
          tenant-id: 88728bcb-d92b-4312-9337-07087ab724f3
        credential:  
          # Specifies your App Registration's Application ID:
          client-id: 58efa4d5-62e8-4b3c-82ac-b0720c84f829
          # Specifies your App Registration's secret key:
        # Specifies the post-log-out-redirect-uri, where to return your app after logout.
        post-logout-redirect-uri: http://localhost:8080
        # Specifies the Microsoft Graph scopes that your app needs access to - not required in this app.
        # authorization-clients:
        #   graph:
        #     scopes: https://graph.microsoft.com/User.Read
      storage:
        blob:
          endpoint: https://memoblob.blob.core.windows.net/
          account-name: memoblob
          account-key: 

# un-comment the following lines if you are deploying to a reverse proxy (e.g. Azure App Service)
# server:
#   forward-headers-strategy: native
#   tomcat:
#     remoteip:
#       protocol-header: "X-Forwarded-Proto"
#       remote-ip-header: "X-Forwarded-For"
#       internal-proxies: ".*"
